[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "debrepoctl"
version = "0.1.0"
description = "Debian repository control tool"
authors = [
    {name = "Serge Kosachiov", email = "skosachiov@gmail.com"},
]
readme = "README.md"
license = {text = "GPL-3.0-only OR BSD-3-Clause"}
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = []
requires-python = ">=3.7"

[project.urls]
Homepage = "https://github.com/skosachiov/debrepoctl"
Repository = "https://github.com/skosachiov/debrepoctl"
"Bug Tracker" = "https://github.com/skosachiov/debrepoctl/issues"

[project.scripts]
debrepoctl = "debrepoctl.debrepoctl:main"

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-data]
"debrepoctl" = ["config/*.conf"]